name: Build and Deploy to Azure

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: leancontainer.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t leancontainer.azurecr.io/lean:${{ github.sha }}
          docker push leancontainer.azurecr.io/lean:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'lean'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'leancontainer.azurecr.io/lean:${{ github.sha }}'
